import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { LocomotiveScrollProvider } from 'react-locomotive-scroll'
import { useEffect, useRef } from 'react'
import { SlideFour, SlideOne, SlideThree, SlideTwo, SlideFive } from '../components/HomeSlides'
import createScrollSnap from 'scroll-snap'

const HomePage = () => {
  const containerRef = useRef(null)

  useEffect(() => {
    const element = containerRef.current
    createScrollSnap(element, {
      snapDestinationY: '90%',
    }, () => console.log('snapped')
    )
  }, [])

  return (
    <body>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div className="pt-10 lg:pt-0 w-fit md:w-full">
        <LocomotiveScrollProvider
          options={
            {
              smooth: true,
            }
          }
          containerRef={containerRef}
          watch={[]}
        >
          <main data-scroll-container ref={containerRef}>
            <SlideOne />
            <SlideTwo />
            <SlideThree />
            <SlideFour />
            <SlideFive />
          </main >
        </LocomotiveScrollProvider >

      </div>

    </body>
  )
}


export default HomePage